spring.application.name=GitMetrics
#spring.datasource.url=jdbc:postgresql://localhost:5432/GitMetrics
#spring.datasource.username=postgres
#spring.datasource.password=aajna


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}
jwt.secret=${JWT_SECRET:OcQnS4m3JjL8Lwz7W0F2M6r3xX0X5Q4rjL3v3jM8mWm0jv2L6Q7S8L8b4L5K5c9Q2W7k0vN2jP1eD8qR4gT6hY9Xw==}